 services:
  app:
    build:
      context: .
      dockerfile: docker/build/Dockerfile
    image: laravel-app
    container_name: laravel_app
    volumes:
      - ./src:/var/www
    ports:
      - "8000:8000"
      - "5173:5173"
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test1234
    ports:
      - "5432:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/templates:/docker-entrypoint-initdb.d
